### PR TITLE
Close more FDs (64 not enough on debian/systemd)

### PR DESCRIPTION
**Pull request by clee**

### CODE REVIEW

**Comment by marcan** [comment]
Sigh, systemd :P

**Comment by Nable80** [comment]
Using <code>/proc/self/fd</code> or at least <code>getrlimit(RLIMIT_NOFILE, &rl)</code> may be better than this guesswork. What possible problems do I miss except increasing code complexity?

I often see similar constructions with brutal loop of ``close(i)`` calls and it keeps me wondering whether there is some better way.

**Comment by marcan** [comment]
Code complexity is not something you want in `init`, as a crash brings down your system.

There is no downside to `close()`ing nonexistent FDs, so there's no reason to inspect `/proc/self/fd` to try to get a list of open FDs. The `RLIMIT_NOFILE` option might be a good idea to set the upper limit to a known max, but I'm not sure if it introduces any other corner cases. The code is intentionally supposed to be as simple as possible.

**Comment by Nable80** [comment]
OK, thank you for this reply.

**Pull request merged**
