### PR TITLE
Make shellcheck happy

### PR DESCRIPTION
**Pull request by szepeviktor**
+ identify the script :)

### CODE REVIEW

**Comment by marcan** [comment]
I don't use shellcheck and this isn't intended as some kind of golden shellscript you can just use as-is. You're expected to understand and modify it as needed. Given that, and that none of the changes here seem to fix actual bugs or significantly improve style, I don't see the point in making it conform to an arbitrary linter's standard.

**Comment by szepeviktor** [comment]
> an arbitrary linter

What linter would you suggest for all of my shell scripts?

**Comment by marcan** [comment]
Whichever one you like, I just don't see why a random script you found on github (especially one as trivial as this) has to make it happy :-)

**Comment by szepeviktor** [comment]
> Whichever one you like

I would really love to know what linter **you** find helpful.

The only bash linter I know is shellcheck. Up to now I use it before committing a script.

**Comment by marcan** [comment]
I do not personally use a linter for shellscripts.

**Comment by szepeviktor** [comment]
Thanks.

**Pull request closed without merging**
